### ISSUE TITLE
Add navigation and onboarding logic

### ISSUE THREAD

**Issue by felipejoglar** [greenpeaksstudio/taskodoro#31]
Add support for navigation and onboarding logic. Also, add conditional navigation if the user has already been onboarded.

### TO-DO
- [x] Add navigation with [PreCompose](https://github.com/Tlaster/PreCompose)
  - [x] Divide the navigation into graphs following https://developer.android.com/guide/navigation/design/type-safety
  - [x] Add [StateHolder](https://github.com/Tlaster/PreCompose/blob/master/docs/component/view_model.md) thing to keep the state
- [x] Add logic to store onboarded state
  - [x] Add [DataStore](https://developer.android.com/jetpack/androidx/releases/datastore) to handle preferences persistence
  - [x] Create onboarding store logic
  - [x] Add saving/retrieving logic from presentation layer
  - [x] Skip onboarding if already done
